apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reposilite
resources:
  - ../../base
patches:
  - path: service-patch.yaml
  - target:
      kind: Deployment
      name: reposilite
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/envFrom

